exporter:
  metrics_port: 10009 # exporter port
  scrape_timeout: 1 # scrape timeout of Prusa Link
  reload_interval: 300 # interval in seconds for config reloader
  log_level: info
  printer_discovery: true
printers:
  buddy:
  - address: <address_of_printer>
    mac: <mac_address_of_printer> # in this case printer discovery would look for printer in network
    username: maker # I'm not aware that there is possibility to change username in XL or MK4 printers - default is maker
    pass: <password>
    name: <your_printer_name>
    type: <mk4 or xl>
  einsy:
  - address: <address_of_printer>
    mac: <mac_address_of_printer> # in this case printer discovery would look for printer in network
    apikey: <your_printer_apikey> # you need to generate api key in printer settings
    name: <your_printer_name>
    type: <mk2.5 or mk3>